receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4320
      http:
        endpoint: 0.0.0.0:4321
  hostmetrics:
    collection_interval: 5s
    scrapers:
      process:
  filelog:
    include: [ /usr/bin/melt-logs/data/linux.log ]
    start_at: beginning

processors:
  resource:
    attributes:
    - key: mw_agent
      action: insert
      value: true
    - key: object_type
      action: insert
      value: process
    - key: service.name
      action: insert
      from_attribute: process.pid

exporters:
  logging:
    loglevel: debug
  otlp/2:
    endpoint: ${OTLP_SERVER_GRPC_ADDR}
    tls:
      insecure: true
    headers:
      authorization: ${MELT_API_TOKEN}

service:
  pipelines:
    metrics:
      receivers: [ hostmetrics ]
      processors: [ resource ]
      exporters: [ logging, otlp/2 ]
    logs:
      receivers: [ filelog ]
      processors: [ resource ]
      exporters: [ logging, otlp/2 ]
