receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4320
      http:
        endpoint: 0.0.0.0:4321

  # Scrapping OS metrics (Infra Metrics)
  hostmetrics:
    collection_interval: 5s
    scrapers:
      process:

  # Read log files (Infra logs + APM logs)
  filelog:
    include: [ /var/log/linux.log ]
    start_at: beginning

  # Read log sent through fluent protocol (APM logs)
  fluentforward:
    endpoint: 0.0.0.0:8006

processors:
  resource:
    attributes:
    - key: mw.account_key
      action: insert
      value: ${MELT_API_KEY}

exporters:
  logging:
    loglevel: debug
  otlp/2:
    endpoint: ${TARGET}
    tls:
      insecure: true
      insecure_skip_verify: true
    headers:
      authorization: ${MELT_API_KEY}

service:
  pipelines:
    metrics:
      receivers: [ hostmetrics, otlp ]
      processors: [ resource ]
      exporters: [ logging, otlp/2 ]
    logs:
      receivers: [ fluentforward, otlp ]
      processors: [ resource ]
      exporters: [ logging, otlp/2 ]
    traces:
      receivers: [ otlp ]
      processors: [ resource ]
      exporters: [ logging, otlp/2 ]