version: "3.4"

services:  
  # Host Agent : Metrics (hostreceivermetrics) + Traces (forwarded via OTLP) + Logs (filelogreceiver)
  mw-agent-host-go:
    container_name: mw-agent-host-go
    image: ghcr.io/middleware-labs/agent-host-go:dev
    command: api-server start
    restart: always
    pid: host
    environment:
      TARGET: host.docker.internal:4317 
      MW_API_KEY: ox83a2gqhp5d8jm03op38c6byy79xrc4ffmx
    ports:
      - 9319:9319
      - 9320:9320
      - 8006:8006
    extra_hosts:
    - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'todo'
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - 3306:3306
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - /usr/local/var/mysql:/var/lib/mysql
      - ./node-apm-demo/todo.sql:/docker-entrypoint-initdb.d/init.sql

  # APM Metrics
  node-apm-demo:
    image: ghcr.io/middleware-labs/agent-node-apm:pkg
    command: node server.js
    environment:
      MW_AUTOGENERATE_TRACING_DATA: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: mw-agent-host-go:9319    # sends data to host agent
      # MW_APM_PAUSE_METRICS: "true"                      # if you want to PAUSE metrics data
      # MW_APM_PAUSE_TRACES: "true"                       # if you want to PAUSE traces data
    depends_on:
      - mysql
    ports:
      - 3002:3002