version: "3.4"
services:  
  melt-agent-host-go:
    # image: ghcr.io/middleware-labs/agent-host-go:dev
    build:
      context: ../../
      dockerfile: Dockerfile
      target: local
    command: api-server start
    restart: always
    pid: host
    ports:
      - 4320:4320
      - 4321:4321
    volumes:
      - ../../:/app
    environment:
      TARGET: http://localhost:4317 
      MELT_API_KEY: ox83a2gqhp5d8jm03op38c6byy79xrc4ffmx
    network_mode: host
  test-apm:
    build:
      context: ./test-apm
      dockerfile: Dockerfile
    command: node movies.js
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4320
    network_mode: host