name: Build & Push Go APT Package - AWS Linux - ARM

on:
  push:
    # branches:
    #   - 'dev'

    tags:
      - 'a-arm*'

env:
  ARCH: arm64
  BINARY_SOURCE: release/mw-go-agent-host-aws-arm
  BINARY_NAME: mw-go-agent-host-aws-arm
  BINARY_TEST: update
  RELEASE_VERSION: 0.0.15-aws-arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: Creating Required Folder Structure
      run: |
        mkdir -p ~/rpmbuild/BUILD
        mkdir -p ~/rpmbuild/BUILDROOT
        mkdir -p ~/rpmbuild/RPMS
        mkdir -p ~/rpmbuild/SOURCES
        mkdir -p ~/rpmbuild/SPECS
        mkdir -p ~/rpmbuild/SRPMS
        mkdir -p ~/rpmbuild/SOURCES/$BINARY_SOURCE-0.0.1
        echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros
        touch ~/rpmbuild/SPECS/test.spec
        cp installables/rpmessentials/test.spec ~/rpmbuild/SPECS/test.spec

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Go Build
      run: |
        GOOS=linux GOARCH=${{ env.ARCH }}  go build -v -a -o ~/rpmbuild/SOURCES/$BINARY_SOURCE-0.0.1/$BINARY_SOURCE
        cd ~/rpmbuild/SOURCES
        tar -czvf $BINARY_SOURCE_0.0.1-1_all.tar.gz $BINARY_SOURCE-0.0.1/
        ls -l ~/rpmbuild/SOURCES/

    - name: Create RPM package
      run: |
        rpmbuild -ba ~/rpmbuild/SPECS/test.spec

    - name: Upload artifacts to Github Pages (install.middleware.io)
      run: |

        git clone https://.:${{ secrets.GHCR_TOKEN }}@github.com/middleware-labs/install.middleware.io.git
        mkdir -p install.middleware.io/rpms
        cp -r ~/rpmbuild/RPMS/x86_64/$BINARY_SOURCE-0.0.1-1.x86_64.rpm install.middleware.io/rpms/
        cd install.middleware.io
        git config --global user.email "keval@middleware.io"
        git config --global user.name "bhogayatakb"
        git add .
        git commit -m "RPM added to install.middleware.io"
        git push origin master
