name: Build & Push Go APT Package

on:
  push:
    # branches:
    #   - 'dev'

    tags:
      - 'aws*'

env:
  ARCH: all
  BINARY_SOURCE: release/mw-go-agent-host-aws
  BINARY_NAME: mw-go-agent-host-aws
  RELEASE_VERSION: 0.0.15

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: Creating Required Folder Structure
      run: |
        mkdir -p example/mw-agent_$RELEASE_VERSION-1_all/usr/bin
        mkdir -p example/mw-agent_$RELEASE_VERSION-1_all/DEBIAN
        mkdir -p example/repos/$RELEASE_VERSION/apt-repo/pool/main/
        mkdir -p example/repos/$RELEASE_VERSION/apt-repo/dists/stable/main/binary-$ARCH

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Go Build
      run: |
        go build -o $BINARY_NAME .

    - name: Create RPM package
      run: |
        rpmbuild -bb \
        --define "_topdir $PWD/rpmbuild" \
        --define "name $BINARY_NAME" \
        --define "version 1.0.0" \
        --define "release 1" \
        rpm/$BINARY_NAME.spec
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: $BINARY_NAME.rpm
        path: rpmbuild/RPMS/x86_64/$BINARY_NAME-1.0.0-1.x86_64.rpm