name: Build & Push Docker Image for Host Agent
on:
  push:
    branches:
     - 'master1'
    #  - 'dev'

env:
  IMAGE_NAME: ghcr.io/middleware-labs/agent-host-go

jobs:
  build-amd64:

    name: Build Docker Image for amd64
    runs-on: ubuntu-latest
    
    steps:
      # Checking out repository code
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Login to ghcr.io
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }} # Consists Github Personal Access Token

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:amd64-${{ github.sha }}
            ${{ env.IMAGE_NAME }}:amd64-latest