name: Build & Push Docker Image for Host Agent
on:
  push:
    branches:
     - 'master'
     - 'dev'

env:
  IMAGE_NAME: ghcr.io/middleware-labs/agent-host-go

jobs:
  build-amd64:

    name: Build Docker Image for amd64
    runs-on: ubuntu-latest
    
    steps:
      # Checking out repository code
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Login to ghcr.io
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }} # Consists Github Personal Access Token

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:amd64-${{ github.sha }}
            ${{ env.IMAGE_NAME }}:amd64-latest
      
  update-configyaml:

    name: Updating otel-config.yaml files in install.middleware.io
    runs-on: ubuntu-latest

    steps:
      - name: Updating otel-config.yaml in install.middleware.io
        run: |
          git clone https://.:${{ secrets.GHCR_TOKEN }}@github.com/middleware-labs/install.middleware.io.git
          cp configyamls/all/otel-config.yaml install.middleware.io/configyamls/all/otel-config.yaml 
          cp configyamls/nodocker/otel-config.yaml install.middleware.io/configyamls/nodocker/otel-config.yaml 
          cd install.middleware.io
          git config --global user.email "keval@middleware.io"
          git config --global user.name "bhogayatakb"
          git add .
          git commit -m "install.middleware.io updated"
          git push origin master    
